// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes =
  | "/"
  | "/about"
  | "/admin"
  | "/admin/menu"
  | "/admin/orders"
  | "/admin/settings"
  | "/admin/users"
  | "/agb"
  | "/auth"
  | "/bubble-waffles-wetzlar"
  | "/checkout"
  | "/confirmation"
  | "/cookie-richtlinie"
  | "/datenschutz"
  | "/eisdiele-wetzlar-special-shakes"
  | "/events-catering-hessen"
  | "/faq"
  | "/firebase-test"
  | "/gutscheine"
  | "/impressum"
  | "/kontakt"
  | "/legal"
  | "/lieferservice-desserts-lahn-dill"
  | "/loyalty"
  | "/menu"
  | "/order-hub"
  | "/order-review"
  | "/order-status"
  | "/password-reset"
  | "/pickup-time"
  | "/poc"
  | "/profile"
  | "/profile/orders"
  | "/reservierung"
  | "/support"
  | "/test-realtime"
  | "/vegane-desserts-wetzlar"
  | "/visit"
  | "/widerruf";
type AppRouteHandlerRoutes = "/api/admin/seed" | "/api/mcp";
type PageRoutes = never;
type LayoutRoutes =
  | "/"
  | "/admin"
  | "/gutscheine"
  | "/legal"
  | "/loyalty"
  | "/order-hub"
  | "/password-reset"
  | "/reservierung"
  | "/support"
  | "/visit";
type RedirectRoutes = never;
type RewriteRoutes = never;
type Routes =
  | AppRoutes
  | PageRoutes
  | LayoutRoutes
  | RedirectRoutes
  | RewriteRoutes
  | AppRouteHandlerRoutes;

interface ParamMap {
  "/": {};
  "/about": {};
  "/admin": {};
  "/admin/menu": {};
  "/admin/orders": {};
  "/admin/settings": {};
  "/admin/users": {};
  "/agb": {};
  "/api/admin/seed": {};
  "/api/mcp": {};
  "/auth": {};
  "/bubble-waffles-wetzlar": {};
  "/checkout": {};
  "/confirmation": {};
  "/cookie-richtlinie": {};
  "/datenschutz": {};
  "/eisdiele-wetzlar-special-shakes": {};
  "/events-catering-hessen": {};
  "/faq": {};
  "/firebase-test": {};
  "/gutscheine": {};
  "/impressum": {};
  "/kontakt": {};
  "/legal": {};
  "/lieferservice-desserts-lahn-dill": {};
  "/loyalty": {};
  "/menu": {};
  "/order-hub": {};
  "/order-review": {};
  "/order-status": {};
  "/password-reset": {};
  "/pickup-time": {};
  "/poc": {};
  "/profile": {};
  "/profile/orders": {};
  "/reservierung": {};
  "/support": {};
  "/test-realtime": {};
  "/vegane-desserts-wetzlar": {};
  "/visit": {};
  "/widerruf": {};
}

export type ParamsOf<Route extends Routes> = ParamMap[Route];

interface LayoutSlotMap {
  "/": never;
  "/admin": never;
  "/gutscheine": never;
  "/legal": never;
  "/loyalty": never;
  "/order-hub": never;
  "/password-reset": never;
  "/reservierung": never;
  "/support": never;
  "/visit": never;
}

export type {
  AppRoutes,
  PageRoutes,
  LayoutRoutes,
  RedirectRoutes,
  RewriteRoutes,
  ParamMap,
  AppRouteHandlerRoutes,
};

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>;
    searchParams: Promise<Record<string, string | string[] | undefined>>;
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>;
    children: React.ReactNode;
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode;
  };

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>;
  }
}
