// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type {
  AppRoutes,
  LayoutRoutes,
  ParamMap,
  AppRouteHandlerRoutes,
} from "./routes.js";
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js";
import type { NextRequest } from "next/server.js";

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    | React.ComponentType<{ params: Promise<ParamMap[Route]> } & any>
    | ((
        props: { params: Promise<ParamMap[Route]> } & any,
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>,
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type RouteHandlerConfig<
  Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes,
> = {
  GET?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  POST?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  PUT?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  PATCH?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  DELETE?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  HEAD?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  OPTIONS?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
};

// Validate ../../src/app/(admin)/admin/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(admin)/admin/menu/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(admin)/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(admin)/admin/orders/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific;
  const handler = {} as typeof import("../../src/app/(admin)/admin/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(admin)/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> =
    Specific;
  const handler =
    {} as typeof import("../../src/app/(admin)/admin/settings/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(admin)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(admin)/admin/users/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/about/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/agb/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agb">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/agb/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/auth/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/bubble-waffles-wetzlar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bubble-waffles-wetzlar">> =
    Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/bubble-waffles-wetzlar/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/checkout/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/confirmation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/confirmation">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/confirmation/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/cookie-richtlinie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookie-richtlinie">> =
    Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/cookie-richtlinie/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/datenschutz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/datenschutz">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/datenschutz/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/eisdiele-wetzlar-special-shakes/page.tsx
{
  type __IsExpected<
    Specific extends AppPageConfig<"/eisdiele-wetzlar-special-shakes">,
  > = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/eisdiele-wetzlar-special-shakes/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/events-catering-hessen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events-catering-hessen">> =
    Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/events-catering-hessen/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/faq/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/firebase-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/firebase-test">> =
    Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/firebase-test/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/gutscheine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gutscheine">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/gutscheine/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/impressum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/impressum">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/impressum/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/kontakt/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kontakt">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/kontakt/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/legal/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/lieferservice-desserts-lahn-dill/page.tsx
{
  type __IsExpected<
    Specific extends AppPageConfig<"/lieferservice-desserts-lahn-dill">,
  > = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/lieferservice-desserts-lahn-dill/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/loyalty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/loyalty">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/loyalty/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/menu">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/menu/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/order-hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-hub">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/order-hub/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/order-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-review">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/order-review/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/order-status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-status">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/order-status/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/password-reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/password-reset">> =
    Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/password-reset/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/pickup-time/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pickup-time">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/pickup-time/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/poc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/poc">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/poc/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/profile/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/orders">> =
    Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/profile/orders/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/profile/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/reservierung/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reservierung">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/reservierung/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/support/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/test-realtime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-realtime">> =
    Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/test-realtime/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/vegane-desserts-wetzlar/page.tsx
{
  type __IsExpected<
    Specific extends AppPageConfig<"/vegane-desserts-wetzlar">,
  > = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/vegane-desserts-wetzlar/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/visit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visit">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/visit/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/widerruf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/widerruf">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/widerruf/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/admin/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/seed">> =
    Specific;
  const handler = {} as typeof import("../../src/app/api/admin/seed/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/mcp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp">> = Specific;
  const handler = {} as typeof import("../../src/app/api/mcp/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(admin)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific;
  const handler = {} as typeof import("../../src/app/(admin)/admin/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/gutscheine/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/gutscheine">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/gutscheine/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/legal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/legal">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/legal/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/loyalty/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/loyalty">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/loyalty/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/order-hub/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/order-hub">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/order-hub/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/password-reset/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/password-reset">> =
    Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/password-reset/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/reservierung/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/reservierung">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/reservierung/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/support/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/support">> = Specific;
  const handler =
    {} as typeof import("../../src/app/(public)/support/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/(public)/visit/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/visit">> = Specific;
  const handler = {} as typeof import("../../src/app/(public)/visit/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific;
  const handler = {} as typeof import("../../src/app/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}
